### ISSUE TITLE
SWC is not up to date with Source

### ISSUE THREAD

**Issue by mbaker3** [rafaelrinaldi/sound-manager#1]
sound-manager.swc in source/swc/ is not up to date with the supplied source code.

For example, the setter for the position property on a SoundItem object does not exist

**Comment by rafaelrinaldi** [comment]
Thanks for the heads up, Mike. It's been a while since I don't make any changes to this library and I'm pretty busy with college stuff right now.

I have some tweaks to add and I'll be updating the .swc on this next release. Feel free to send me a pull request though.

Cheers.
